# Generated by Django 3.1.5 on 2021-01-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_auto_20210128_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='monto_bebida',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='tamanopizza',
            name='monto_tamano',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='toppin',
            name='monto_toppin',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
